### ISSUE TITLE
Exception with column[number][data] = null. request string

### ISSUE THREAD

**Issue by helios-ag** [arodygin/datatables-bundle#1]
Datatables v.1.10.13
DataTablesBundle v.2.1.2
with following example 
https://datatables.net/examples/ajax/null_data_source.html
Datatables bundle raises constraint violation:
"This value should be greater than or equal to "0""

**Comment by webinarium** [comment]
Thank you for the bug report. I never used that feature of the DataTables and wasn't aware that column data can be empty. Anyway, this is fixed now - I have just released new version 2.1.3.

**Comment by helios-ag** [comment]
Thank you for quick fix!
