### ISSUE TITLE
This value cannot be null

### ISSUE THREAD

**Issue by flebas** [arodygin/datatables-bundle#10]
Hello, 

I am trying to implement your example with UsersDataTable. 
When calling usersAction, I get an error "this value cannot be null". 

Service with id "users" is added in DataTables->addServices
Error occurs DataTables->handle function because $params->draw, starts, ... are null and don't pass vaidation. 

I should have missed something. 

I am using Symfony 3.4 with PHP 7.1

Thank you.

**Comment by webinarium** [comment]
Hello,

Sorry, I'm not sure what's happening, let me please try to replicate it first, using the same Symfony version.

1. Do you use DataTables-service autoloading, or do you configure it manually?
2. What is the DataTables version you use? I mean jQuery plugin's version, e.g. `1.10.18`.

Best regards,
Artem

**Comment by flebas** [comment]
Hello, 

I use autoloading and I can see in debugger that service is loaded. 
DataTables version is 1.10.19
It seems it is an AJAX problem. 

Best regards, 
Frederic

**Comment by flebas** [comment]
Hello, 
I have switched to another solution. 
Don't waste your time on my problem. 
Regards, 
Frederic
