### ISSUE TITLE
Update Example

### ISSUE THREAD

**Issue by laurentmuller** [arodygin/datatables-bundle#11]
Version: 2.3.1
Bug: No

Description:
In your example, You set filtered count after sorting the columns. But this is not necessary because the number of records are the same and the query is slower. 

So call first:
<pre>
// Get filtered count.
$queryCount = clone $query;
....
</pre>
Then;
<pre>
// Order.
foreach ($request->order as $order) {
....
</pre>

Thank You for your excellent bundle !!

**Comment by webinarium** [comment]
You are right - I have updated the example, thank you!
