### ISSUE TITLE
Error when no sorting column

### ISSUE THREAD

**Issue by laurentmuller** [arodygin/datatables-bundle#13]
When a data table does not contains any sorted column, the Ajax request returns `null` for the `order` parameter. 

Options:
```javascript
$('myTable').DataTable({
    sort: []
    // or
    ordering: false
});

```
When calling function:
```php
public function handle(Request $request, string $id): DataTableResults
{
    ...
   $params->order = $request->get('order');
    ...
}
```
And why the order is `null`, a violation occurs (`This value should not be null.`) for this parameter.

Maybe You can give a default value for this parameter so the violation is not raised:
```php
$params->order = $request->get('order', []);
```
Or You can check if all columns parameter are not sortable and adjust the `order` value accordingly.

Version used: 2.3.2

**Comment by webinarium** [comment]
Thank you for the bug report. I've fixed this as you suggested and released in new version 2.3.3.
