### ISSUE TITLE
Better pagination 

### ISSUE THREAD

**Issue by aanyszek** [arodygin/datatables-bundle#5]
Hello. 

Best DT bundle for symfony but please update Wiki page, section with pagination. 
Take my example: 

   
        ...

         /**
         * Clone for take count
         */
        $queryCount = clone  $query;

        /**
         * Get paginated data
         */
        $query->setMaxResults($request->length);
        $query->setFirstResult($request->start);

        /** @var \AppBundle\Entity\Package[] $users */
        $entities = $query->getQuery()->getResult();

        foreach ($entities as $entity) {
            $results->data[] =
                $this->getRow($entity);
        }

        /**
         * Get filtered count
         */
        $queryCount->select("count(p.id)");
        $count = $queryCount->getQuery()->getSingleScalarResult();
        $results->recordsFiltered = $count;

        ...

Your code: 

        /** @var \AppBundle\Entity\User[] $users */
        $users = $query->getQuery()->getResult();

        $results->recordsFiltered = count($users);

        for ($i = 0; $i < $request->length || $request->length == -1; $i++) {

            $index = $i + $request->start;

            if ($index >= $results->recordsFiltered) {
                break;
            }

            $user = $users[$index];

            $results->data[] = [
                $user->getId(),
                $user->getLogin(),
                $user->getFullname(),
            ];
        }

**Comment by webinarium** [comment]
Good point! I have updated the wiki page, thank you.
